<?xml version="1.0" encoding="utf-8"?><Database Name="GoodEatsFarm" Class="GoodEatsFarmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=198.71.225.145;Initial Catalog=GoodEatsFarm;Persist Security Info=True;User ID=rusty" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GoodEatsFarmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SuperCategoryID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Category_Category" Member="Categories" ThisKey="CategoryID" OtherKey="SuperCategoryID" Type="Category" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Product" />
      <Association Name="Category_Category" Member="Category1" ThisKey="SuperCategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="New_NewsImg" Member="NewsImgs" ThisKey="NewsID" OtherKey="NewsID" Type="NewsImg" />
    </Type>
  </Table>
  <Table Name="dbo.NewsImgs" Member="NewsImgs">
    <Type Name="NewsImg">
      <Column Name="NewsImgID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="New_NewsImg" Member="New" ThisKey="NewsID" OtherKey="NewsID" Type="New" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.uspProductInsert" Method="uspProductInsert">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PriceInfo" Parameter="priceInfo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CategoryID" Parameter="categoryID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ImagePath" Parameter="imagePath" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspProductsDropSingle" Method="uspProductsDropSingle">
    <Parameter Name="ProductID" Parameter="productID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspProductsGetSingle" Method="uspProductsGetSingle">
    <Parameter Name="ProductID" Parameter="productID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspProductsGetSingleResult">
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspProductUpdate" Method="uspProductUpdate">
    <Parameter Name="ProductID" Parameter="productID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PriceInfo" Parameter="priceInfo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ImagePath" Parameter="imagePath" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="OrderIndex" Parameter="orderIndex" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspProductsGetbyCat" Method="uspProductsGetbyCat">
    <Parameter Name="CategoryID" Parameter="categoryID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspProductsGetbyCatResult">
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspNewsAndPicsDelete" Method="uspNewsAndPicsDelete">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspNewsGetByYear" Method="uspNewsGetByYear">
    <Parameter Name="Year" Parameter="year" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="uspNewsGetByYearResult">
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspNewsGetSingle" Method="uspNewsGetSingle">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspNewsGetSingleResult">
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspNewsGetTopSeven" Method="uspNewsGetTopSeven">
    <ElementType Name="uspNewsGetTopSevenResult">
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspNewsPicAdd" Method="uspNewsPicAdd">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspNewsPicDelete" Method="uspNewsPicDelete">
    <Parameter Name="NewsImgID" Parameter="newsImgID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspNewsPicsGetByArticle" Method="uspNewsPicsGetByArticle">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspNewsPicsGetByArticleResult">
      <Column Name="NewsImgID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspNewsUpdate" Method="uspNewsUpdate">
    <Parameter Name="NewsID" Parameter="newsID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NewsContent" Parameter="newsContent" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NewsDate" Parameter="newsDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspNewsInsert" Method="uspNewsInsert">
    <Parameter Name="NewsContent" Parameter="newsContent" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NewsDate" Parameter="newsDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="uspNewsInsertResult">
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>